#!/usr/bin/bash

# Definir la variable con la ruta de los wallpapers si no está definida
WALLPAPER_DIR="${WALLPAPER_DIR:-$HOME/Imágenes/Wallpapers}"

# Verificar si la carpeta existe
if [ ! -d "$WALLPAPER_DIR" ]; then
    echo "Error: WALLPAPER_DIR no existe o no es un directorio."
    exit 1
fi

# Inicializar swww si es necesario
swww query || swww init

# Seleccionar una imagen aleatoria y establecerla como fondo de pantalla
IMAGE=$(find "$WALLPAPER_DIR" -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \) | shuf -n 1)

if [ -z "$IMAGE" ]; then
    echo "Error: No se encontraron imágenes en $WALLPAPER_DIR"
    exit 1
fi

swww img "$IMAGE" --transition-fps 60 --transition-type grow --transition-pos 0.925,0.977 --transition-duration 2

